detector_backend: insightface
embedder_backend: insightface
cluster_method: agglomerative
distance_threshold: 0.4
dbscan_eps: 0.38
dbscan_min_samples: 3
min_cluster_size: 3
min_score: 0.85
batch_size: 16
max_size: 2048
assign_threshold: 0.6
near_dup_threshold: 0.98
allow_coreml: true
copy_originals: false
detect_only: false
save_annots: false
bench: false
resume: false
incremental: false
people_dir: null
detections_json: null
crop_size: null
verbose: false
