name: Daily Test Suite

on:
  schedule:
    # Run at 9 AM, 1 PM, and 5 PM Eastern Time
    # GitHub Actions uses UTC, so convert ET to UTC:
    # 9 AM ET = 1 PM UTC, 1 PM ET = 5 PM UTC, 5 PM ET = 9 PM UTC
    - cron: "0 13,17,21 * * *" # 1 PM, 5 PM, 9 PM UTC = 9 AM, 1 PM, 5 PM ET
  workflow_dispatch: # Allow manual triggering

jobs:
  test-suite:
    runs-on: macos-latest # Match your development environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Create test data directory
        run: mkdir -p data/test_data

      - name: Run full test suite
        run: |
          echo "🧪 Running comprehensive test suite..."
          python -m pytest scripts/tests/ -v --tb=short --durations=10

      - name: Run validation checks
        run: |
          echo "🔍 Running validation checks..."
          python scripts/tests/test_inline_validation.py
          python scripts/tests/test_file_safety_audit.py

      - name: Generate test report
        run: |
          echo "📊 Generating test report..."
          mkdir -p test-results
          python -m pytest scripts/tests/ --junitxml=test-results/test-results.xml --cov=scripts --cov-report=xml:test-results/coverage.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ github.run_id }}
          path: test-results/

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Test suite failed!"
          # In a real setup, you could add Slack/email notifications here
          echo "Check the test results for details."

      - name: Notify on success
        if: success()
        run: |
          echo "✅ All tests passed!"
          echo "System health: GOOD"
